---
title: "Week 2 - Linear Regression"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

This week is a half week because of Labor Day. There will be no class Monday, and the Thursday class will be labs about linear regression to accompany the lecture from last week.

If you need a reminder this is the reading about linear regression models.

Read chapter 3 of "An Introduction to Statistical Learning". This chapter goes over simple linear regression, multiple linear regression, and the considerations used in linear regression. As far as I can tell, you have all taken courses where linear regression has been introduced. It is still worthwhile for you to read this chapter to get familiar with the book, and hopefully, it will be an easy read.

If you want more information about the way to fit a model using the tidymodels, read chapter 6 of Tidy Modeling with R, [Fitting models with parsnip](https://www.tmwr.org/models.html).

If you want more information on the theoretical background you can read sections 3.1 and 3.2 of "The Elements of Statistical Learning". This is optional reading.

Instead of reading the lab sections of chapter 3, read [this](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/linear-regression.html) chapter instead which I rewrote to use tidymodels.
